title: "Sreekutty's Portfolio"
description: "Showcasing my Data Science Projects and Skills"
theme: jekyll-theme-cayman  # You can also try jekyll-theme-minimal, jekyll-theme-slate, or jekyll-theme-midnight
author: "Sreekutty"
